server:
  port: 8081
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Opsord/TINGESO-EV-02
          search-paths: "TopEducationApp/config-data"