apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-office-deployment
  labels:
    app: admin-office-deployment
spec:
  selector:
    matchLabels:
      app: admin-office-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-office-deployment
    spec:
      containers:
        - name: tem-adminoffice-service
          image: opsord/tem-adminoffice-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-office-service
  labels:
    app: admin-office-service
spec:
  selector:
    app: admin-office-deployment
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer