apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  # Students database
  POSTGRES_DB_STUDENTS: tem-students
  # Scores database
  POSTGRES_DB_SCORES: tem-scores
  # Installments database
  POSTGRES_DB_INSTALLMENTS: tem-installments